# Generated by Django 5.0.2 on 2024-05-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
    ]
