# Generated by Django 5.0.2 on 2024-05-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therest', '0003_alter_booking_client_alter_booking_managed_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therest.userprofile'),
        ),
        migrations.AlterField(
            model_name='booking_managed',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therest.userprofile'),
        ),
    ]
