# Generated by Django 5.0.2 on 2024-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therest', '0004_alter_booking_client_alter_booking_managed_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ora',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
